kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-eks-full-access
provisioner: efs.csi.aws.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: efs-eks-pv-pod   # Adjusted the name to something unique
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-eks-access
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-040a50fd058340c7e::fsap-0f4cfeaf4640179e3  # Create an access in your EFS
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-claim100
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-eks-access
  resources:
    requests:
      storage: 50Gi

